name: release

on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: docker/setup-qemu-action@v2

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install cython==0.29.34 && pip install -e . && python build.py
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests
          CIBW_SKIP: pp*
          CIBW_ARCHS_LINUX: x86_64 aarch64

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl

  upload:
    # Skip this step on pull requests. Run only when pushing a version tag.
    if: startsWith(github.ref, 'refs/tags/v')
    needs: builds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Stage wheels
      uses: actions/download-artifact@v3
      with:
        name: wheelhouse
        path: wheelhouse
    - run: |
        mkdir dist
        mv -v wheelhouse/* dist/
        ls -l dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
       user: __token__
       password: ${{ secrets.PYPI_API_TOKEN }}
